#!groovy

// Generated by IBM TransformationAdvisor
// Mon May 27 05:34:01 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'samplesgallery'
    mvnCommands = '--version'
    test='false'
}